name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Publish the release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0.2
          files: Release.txt

#      - name: Build the Docker image
#        run: docker build -t ninja scripts
#      - name: Build the project
#        run: docker run --rm -v ./:/app ninja scripts/compile.sh
#      - name: Publish the release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: 1.0.0
