name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5
      - name: Build the Docker image
        run: docker build -t ninja scripts
      - name: Build the project
        run: docker run --rm -v ./:/app ninja scripts/compile.sh
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          artifacts: ./build/x86_64-linux-gnu/ninja
