name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Upload the binaries
        uses: actions/upload-artifact@v4
        with:
          name: Release.txt
          path: Release.txt
          compression-level: 0
      - name: Publish the release
        uses: ncipollo/release-action@v1
        with:
          tag: 1.0.0
          allowUpdates: true
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          artifacts: ./Release.txt

#      - name: Build the Docker image
#        run: docker build -t ninja scripts
#      - name: Build the project
#        run: docker run --rm -v ./:/app ninja scripts/compile.sh
#      - name: Publish the release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: 1.0.0
