name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5
      - name: Build the Docker image
        run: docker build -t ninja scripts
      - name: Build the project
        run: docker run -it --rm -v ./:/app ninja scripts/compile.sh
