name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get the latest version
        run: |
          VERSION=$(basename $(curl -sILo /dev/null -w '%{url_effective}' https://github.com/ninja-build/ninja/releases/latest))
          ARTIFACT=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION | grep -o linux || true)
          printf "VERSION=$VERSION\nARTIFACT=$ARTIFACT\n" >> $GITHUB_ENV
      - name: Clone the repository
        if: env.ARTIFACT == ''
        uses: actions/checkout@v7
      - name: Build the Docker image
        if: env.ARTIFACT == ''
        run: ./setup.sh build-image
      - name: Build the application
        if: env.ARTIFACT == ''
        run: ./setup.sh build-app
      - name: Publish the release
        if: env.ARTIFACT == ''
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.VERSION }}
          body: "[Release notes](https://github.com/ninja-build/ninja/releases/tag/${{ env.VERSION }})"
          files: ./build/*
