name: macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Get the latest version
        run: |
          VERSION=$(basename $(curl -sILo /dev/null -w '%{url_effective}' https://github.com/ninja-build/ninja/releases/latest))
          ARTIFACT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION | grep -om1 macos || true)
          printf "VERSION=$VERSION\nARTIFACT=$ARTIFACT\n" >> $GITHUB_ENV
      - name: Clone the repository
        if: env.ARTIFACT == ''
        uses: actions/checkout@v7
      - name: Install the tools
        if: env.ARTIFACT == ''
        run: brew install re2c
      - name: Build the application
        if: env.ARTIFACT == ''
        run: ./scripts/macos/compile.sh
      - name: Publish the release
        if: env.ARTIFACT == ''
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.VERSION }}
          body: "[Release notes](https://github.com/ninja-build/ninja/releases/tag/${{ env.VERSION }})"
          files: ./build/*
