name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5
      - name: Install the tools
        run: choco install re2c
      - name: Build the application
        run: .\scripts\compile.bat
