name: Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Get the latest version
        shell: bash
        run: |
          VERSION=$(basename $(curl -sILo /dev/null -w '%{url_effective}' https://github.com/ninja-build/ninja/releases/latest))
          ARTIFACT=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION | grep -om1 windows || true)
          printf "VERSION=$VERSION\nARTIFACT=$ARTIFACT\n" >> $GITHUB_ENV
      - name: Clone the repository
        if: env.ARTIFACT == ''
        uses: actions/checkout@v7
      - name: Install the tools
        if: env.ARTIFACT == ''
        run: choco install re2c
      - name: Build the application
        if: env.ARTIFACT == ''
        run: .\scripts\windows\compile.ps1 "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build"
      - name: Publish the release
        if: env.ARTIFACT == ''
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.VERSION }}
          body: "[Release notes](https://github.com/ninja-build/ninja/releases/tag/${{ env.VERSION }})"
          files: ./build/*
